"""add company image_path and short_description columns, add industry constraint

Revision ID: 3e08a3c5d30f
Revises: add_link_to_notification
Create Date: 2025-04-29 09:32:54.342416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e08a3c5d30f'
down_revision = 'add_link_to_notification'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.String(length=200), nullable=True))
        
        # 業種の制約を追加
        batch_op.create_check_constraint(
            'check_industry_values',
            'industry IN (\'none\', \'manufacturing\', \'retail\', \'service\', \'it\', \'construction\', \'food\', \'real_estate\', \'medical\', \'education\', \'agriculture\', \'other\')'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('check_industry_values', type_='check')
        batch_op.drop_column('short_description')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
